<?php

namespace Asbo\WhosWhoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraRepository extends EntityRepository
{
}
